"""add_pipeline_fields_to_invoices

Revision ID: 3852f74b498a
Revises: 3ea0a8e64e36
Create Date: 2026-04-03 22:27:02.460269

BUG-D1: down_revision updated from eaeb574c5dc3 to 3ea0a8e64e36.
The two intermediate no-op duplicates (6ef6ff8a213f, eaeb574c5dc3) have been
deleted and the chain compressed to a single canonical error_detail migration.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3852f74b498a'
down_revision: Union[str, Sequence[str], None] = '3ea0a8e64e36'  # BUG-D1: was eaeb574c5dc3
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('ingestion_method', sa.String(), nullable=True))
    op.add_column('invoices', sa.Column('gst_rules_json', sa.JSON(), nullable=True))
    op.add_column('invoices', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.add_column('invoices', sa.Column('processing_time_ms', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invoices_idempotency_key'), 'invoices', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_idempotency_key'), table_name='invoices')
    op.drop_column('invoices', 'processing_time_ms')
    op.drop_column('invoices', 'idempotency_key')
    op.drop_column('invoices', 'gst_rules_json')
    op.drop_column('invoices', 'ingestion_method')
    op.drop_column('invoices', 'source_type')
    # ### end Alembic commands ###
