"""add_error_detail_column_to_invoices

Revision ID: 3ea0a8e64e36
Revises: 2cbea98c402b
Create Date: 2026-04-02 15:48:36.038247

BUG-D1: This is the canonical single migration that adds error_detail.
Revisions 6ef6ff8a213f and eaeb574c5dc3 were no-op duplicates with the same
description; they have been deleted and the chain rewired through this file.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea0a8e64e36'
down_revision: Union[str, Sequence[str], None] = '2cbea98c402b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('error_detail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'error_detail')
    # ### end Alembic commands ###
